---
- hosts: cvslurm23-compute
  remote_user: centos
  become: yes
  become_user: root
  tasks:

  - name: create mountpoint for the shared software
    file:
      path: /srv/sw/eb
      state: directory
      mode: 0755
      recurse: yes

  - name: mount shared sw folder
    mount:
      name: /srv/sw/eb
      src: 'frontend001:/srv/sw/eb'
      fstype: nfs
      opts: ro,async,auto
      state: mounted

  - name: add easybuild installpath to Lmod MODULEPATH automatically
    copy:
      src: cluster_conf-data/z00-modulepath-cluster.sh
      dest: /etc/profile.d/z00-modulepath.sh
      mode: 0755
