---
- hosts: cvslurm23-frontend
  remote_user: centos
  become: yes
  tasks:

  - name: create folder for Java tarball
    file:
      path: /usr/easybuild/easyconfigs/j/Java/j/Java/
      state: directory
      owner: centos
      group: vanloo
      mode: 0755

  - name: put downloaded jdk-8u112 tarball in place for install
    copy:
      src: instance_conf-data/jdk-8u112-linux-x64.tar.gz
      dest: /usr/easybuild/easyconfigs/j/Java/j/Java/jdk-8u112-linux-x64.tar.gz
      force: no

  - name: put downloaded R-3.2.3-foss-2016a.eb in place for install
    copy:
      src: instance_conf-data/R-3.2.3-foss-2016a.eb
      dest: /home/centos/R-3.2.3-foss-2016a.eb
      force: no

  - name: put downloaded R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb in place for install
    copy:
      src: instance_conf-data/R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb
      dest: /home/centos/R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb
      force: no

  - name: put downloaded GCCcore-4.9.3.eb in place for install
    copy:
      src: instance_conf-data/GCCcore-4.9.3.eb
      dest: /home/centos/GCCcore-4.9.3.eb
      force: no

  - name: install Java with easybuild
    become_user: centos
    command: eb Java-1.8.0_112.eb --robot

  - name: install R and Bioconductor via easybuild
    become_user: centos
    command: eb /home/centos/GCCcore-4.9.3.eb /home/centos/R-3.2.3-foss-2016a.eb /home/centos/R-bundle-Bioconductor-3.2-foss-2016a-R-3.2.3.eb --robot

  - name: download rstudio-server
    get_url:
      url: https://download2.rstudio.org/rstudio-server-rhel-1.0.136-x86_64.rpm
      dest: /home/centos/rstudio-server-rhel-1.0.136-x86_64.rpm

  - name: install rstudio server
    yum:
      name: /home/centos/rstudio-server-rhel-1.0.136-x86_64.rpm
      disable_gpg_check: yes
      state: present

  - name: configure rstudio-server
    lineinfile:
      name: /etc/rstudio/rserver.conf
      line: 'rsession-which-r=/srv/sw/eb/software/R/3.2.3-foss-2016a/bin/R'

  - name: start rstudio-server
    command: rstudio-server start
