---
#
# This playbook together with its second part, will configure 
# an instance according to the vanloo lab specs: installing 
# software, users, keys etc and attaching shared volumes.
#
#
- name: Configure instance
  tags:
    - vanloo
  hosts: all
  remote_user: centos
  become: yes
  become_user: root
  roles: []
  tasks:
  - name: upgrade all packages
    yum:
      name: '*'
      state: latest

  - name: install yum packages
    yum:
      name: screen,vim-enhanced,tmux,sysstat,wget,unzip,epel-release

  - name: install yum Development Tools
    yum:
      name: "@Development tools"

  - name: install more yum packages
    yum:
      name: python-pip,python-wheel,zsh,Lmod,htop,iotop,libibverbs,libibverbs-devel,openssl-devel,tcl-devel,tk-devel,pango-devel,libffi,psmisc,rrdtool,xz-devel,zlib,zlib-devel,lsof,libXtst,libXt,libXmu

  - name: update pip and setuptools
    command: pip install -U pip setuptools

  - name: install virtualenv
    command: pip install virtualenv

  - name: install easybuild via pip
    pip:
      name: EasyBuild

  - group:
      name: vanloo
      state: present
      gid: 1002

  - name: create easybuild installation folder
    file:
      path: /srv/sw/eb/
      state: directory
      owner: centos
      group: vanloo
      mode: 0775

  - name: create easybuild.d config folder
    file:
      path: /etc/easybuild.d/
      state: directory

  - name: put easybuild.cfg file in place
    copy:
      src: modules.cfg
      dest: /etc/easybuild.d/modules.cfg
      mode: 0644

  - name: put ifcfg-eth1 file in place
    copy:
      src: ifcfg-eth1
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      mode: 0644

  - name: add easybuild installpath to Lmod MODULEPATH automatically
    copy:
      src: z00-modulepath.sh
      dest: /etc/profile.d/z00-modulepath.sh
      mode: 0644


  - include_vars: users.yml

  - name: Add users | create users, shell, home dirs
    user: name={{ item.username }} uid={{ item.userid }} shell=/bin/bash createhome=yes group=vanloo password={{ user_pass }} comment='create with ansible'
    with_items: '{{users}}'

  - name: Setup | authorized key upload
    authorized_key: user={{ item.username }}
      key="{{ lookup('file', 'pub_keys/{{ item.username }}.pub') }}"
    with_items: '{{users}}'

  - name: Sudoers | add users to wheel
    user: name={{ item.username }} append=yes groups=vanloo,wheel
    when: item.use_sudo == True
    with_items: '{{users}}'

  - name: restarting network service
    service:
      name: network
      state: restarted

  - name: make sure DNS settings are correct
    lineinfile:
      path: /etc/resolv.conf
      regexpr: '^nameserver'
      line: 'nameserver 8.8.8.8'
      owner: root
      group: root
      mode: 0644
