---
- hosts: all
  remote_user: centos
  become: yes
  tasks:

  - name: create mountpoint for the shared storage
    file:
      path: /srv/shared
      state: directory
      owner: centos
      group: vanloo
      mode: 0755

  - name: mount shared storage
    mount:
      name: /srv/shared
      src: 10.248.192.54:/emed/bulk/tcga-test
      fstype: nfs
      opts: defaults
      state: mounted


  - name: Copy new easyconfigs and sources (GATK + Java)
    copy:
      src: /home/jdemeul/instance_config/easyconfigs
      dest: /home/centos/

  - name: install easybuild packages
    become_user: centos
    command: "eb {{ item }} -r"
    with_items:
      - Java-1.8.0_141.eb
      - R-3.4.1-foss-2016b-X11-20160819.eb
      - R-bundle-Bioconductor-3.5-foss-2016b-R-3.4.1.eb
      - BWA-0.7.15-foss-2016b.eb
      - TopHat-2.1.1-foss-2016b.eb
      - Bowtie2-2.2.9-foss-2016b.eb
      - BEDTools-2.26.0-foss-2016b.eb
      - SAMtools-1.4-foss-2016b.eb
      - IMPUTE2-2.3.2_x86_64_dynamic.eb
      - GATK-3.8-Java-1.8.0_141.eb
      - picard-2.10.10-Java-1.8.0_141.eb
      - Circos-0.69-5-foss-2016b-Perl-5.24.0.eb
      - Python-3.5.2-foss-2016b.eb

  - name: download rstudio-server
    get_url:
      url: https://download2.rstudio.org/rstudio-server-rhel-1.0.153-x86_64.rpm
      dest: /home/centos/rstudio-server-rhel-1.0.153-x86_64.rpm

  - name: install rstudio server
    yum:
      name: /home/centos/rstudio-server-rhel-1.0.153-x86_64.rpm
      disable_gpg_check: yes
      state: present

  - name: configure rstudio-server
    lineinfile:
      name: /etc/rstudio/rserver.conf
      line: 'rsession-which-r=/srv/sw/eb/software/R/3.4.1-foss-2016b-X11-20160819/bin/R'

  - name: start rstudio-server
    command: rstudio-server start
