---
#
# This playbook is for site-local customization to ElastiCluster's
# playbooks.  It runs *after* any other playbook distributed with
# ElastiCluster has gotten its chance to run.
#
# An empty playbook is checked into the Git repository.  If you make
# any local modifications, please run `git update-index
# --assume-unchanged after.yml` to avoid committing them accidentally
# into ElastiCluster's main branch.
#
- name: Apply local customizations (after)
  tags:
    - after
    - local
  hosts: all
  # by default these are no-op (empty task list)
  roles: []
  tasks:
  - name: put ifcfg-eth1 file in place
    copy:
      force: no
      src: /home/jdemeul/instance_config/ifcfg-eth1
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      mode: 0644

  - name: bring eth1 up
    shell: |
      ip a show eth1 up || ifup eth1

  - name: reapply correct DNS settings
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: 'nameserver 8.8.8.8'
      owner: root
      group: root
      mode: 0644

  - group:
      name: vanloo
      state: present
      gid: 1002

  - include_vars: /home/jdemeul/instance_config/users.yml

  - name: Add users | create users, shell, home dirs
    user: name={{ item.username }} uid={{ item.userid }} shell=/bin/bash createhome=yes group=vanloo password={{ user_pass }} comment='create with ansible'
    with_items: '{{users}}'

  - name: Setup | authorized key upload
    authorized_key: user={{ item.username }}
      key="{{ lookup('file', '/home/jdemeul/instance_config/pub_keys/{{ item.username }}.pub') }}"
    with_items: '{{users}}'

  - name: Sudoers | add users to wheel
    user: name={{ item.username }} append=yes groups=vanloo,wheel
    when: item.use_sudo == True
    with_items: '{{users}}'

  - name: create mountpoint for the shared storage
    file:
      path: /srv/shared
      state: directory
      owner: centos
      group: vanloo
      mode: 0755

  - name: create easybuild installation folder
    file:
      path: /srv/sw/eb/
      state: directory
      owner: centos
      group: vanloo
      mode: 0755

  - name: mount shared storage
    mount:
      name: /srv/shared/
      src: 10.248.192.54:/emed/bulk/tcga-test
      fstype: nfs
      opts: defaults
      state: mounted

  - name: install yum Development Tools
    yum:
      name: "@Development tools"

  - name: install more yum packages
    yum:
      name: screen,vim-enhanced,tmux,sysstat,wget,unzip,python-pip,python-wheel,Lmod,zlib,zlib-devel,lsof,htop,iotop,libibverbs,libibverbs-devel,openssl-devel,tcl-devel,tk-devel,pango-devel,libffi,psmisc,rrdtool,xz-devel,libXtst,libXt,libXmu


- name: Apply frontend customizations (after)
  tags:
    - after
    - local
  hosts: slurm_master
  tasks:

  - include_vars: /home/jdemeul/instance_config/users.yml

  - name: Create vanloo account for cluster
    tags:
      - slurm
    shell: |
      sacctmgr --immediate --parsable --noheader list account Cluster=elasticluster  | grep '^vanloo|' \
        || sacctmgr -i --quiet add account vanloo Cluster=elasticluster

  - name: Add users to slurm accounting
    tags:
      - slurm
    shell: |
      sacctmgr --immediate --parsable --noheader list user Account='{{item.username}}' | grep '^{{item.username}}|' \
        || sacctmgr --immediate --quiet add user '{{item.username}}' DefaultAccount=vanloo
    with_items: '{{users}}'

  - name: update pip and setuptools
    command: pip install -U pip setuptools

  - name: install virtualenv
    command: pip install virtualenv

  - name: install easybuild via pip
    pip:
      name: EasyBuild

  - name: create easybuild.d config folder
    file:
      path: /etc/easybuild.d/
      state: directory

  - name: put easybuild.cfg file in place
    copy:
      force: no
      src: /home/jdemeul/instance_config/modules-cluster.cfg
      dest: /etc/easybuild.d/modules.cfg
      mode: 0644

  - name: add easybuild installpath to Lmod MODULEPATH automatically
    copy:
      src: /home/jdemeul/instance_config/z00-modulepath-cluster.sh
      dest: /etc/profile.d/z00-modulepath.sh
      mode: 0644

  - name: adding sw mount to exports
    lineinfile:
      name: /etc/exports
      line: '/srv/sw/eb compute001(ro,no_root_squash,async,no_subtree_check,crossmnt) compute002(ro,no_root_squash,async,no_subtree_check,crossmnt)'

  - name: export sw
    command: exportfs -a


- name: Apply worker customizations (after)
  tags:
    - after
    - local
  hosts: slurm_worker
  tasks:

  - name: mount shared sw folder
    mount:
      name: /srv/sw/eb
      src: 'frontend001:/srv/sw/eb'
      fstype: nfs
      opts: ro,async,auto
      state: mounted

  - name: add easybuild installpath to Lmod MODULEPATH automatically
    copy:
      force: no
      src: /home/jdemeul/cluster_conf-data/z00-modulepath-cluster.sh
      dest: /etc/profile.d/z00-modulepath.sh
      mode: 0644


- name: Apply final frontend customizations (after)
  tags:
    - local
    - after
  hosts: slurm_master
  tasks:

  - name: Copy new easyconfigs and sources (GATK + Java)
    copy:
      src: /home/jdemeul/instance_config/easyconfigs
      dest: /home/centos/

  - name: install easybuild packages
    become_user: centos
    command: "eb {{ item }} -r"
    with_items:
      - Java-1.8.0_141.eb
      - R-3.4.1-foss-2016b-X11-20160819.eb
      - R-bundle-Bioconductor-3.5-foss-2016b-R-3.4.1.eb
      - BWA-0.7.15-foss-2016b.eb
      - TopHat-2.1.1-foss-2016b.eb
      - Bowtie2-2.2.9-foss-2016b.eb
      - BEDTools-2.26.0-foss-2016b.eb
      - SAMtools-1.4-foss-2016b.eb
      - IMPUTE2-2.3.2_x86_64_dynamic.eb
      - GATK-3.8-Java-1.8.0_141.eb
      - picard-2.10.10-Java-1.8.0_141.eb
      - Circos-0.69-5-foss-2016b-Perl-5.24.0.eb
      - Python-3.5.2-foss-2016b.eb

  - name: download rstudio-server
    get_url:
      url: https://download2.rstudio.org/rstudio-server-rhel-1.0.153-x86_64.rpm
      dest: /home/centos/rstudio-server-rhel-1.0.153-x86_64.rpm

  - name: install rstudio server
    yum:
      name: /home/centos/rstudio-server-rhel-1.0.153-x86_64.rpm
      disable_gpg_check: yes
      state: present

  - name: configure rstudio-server
    lineinfile:
      name: /etc/rstudio/rserver.conf
      line: 'rsession-which-r=/srv/sw/eb/software/R/3.4.1-foss-2016b-X11-20160819/bin/R'

  - name: start rstudio-server
    command: rstudio-server start
